[build]
  command = "ng build ui-lib --configuration production && ng build demo-app --configuration production"
  publish = "dist/demo-app/browser"

[build.environment]
  ANGULAR_PROJECT = "demo-app"

[[plugins]]
  package = "@netlify/angular-runtime"